/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.timesheet.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimesheetDetails service. Represents a row in the &quot;intranet_timesheet_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link sg.com.para.intranet.timesheet.services.model.impl.TimesheetDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link sg.com.para.intranet.timesheet.services.model.impl.TimesheetDetailsImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see TimesheetDetails
 * @see sg.com.para.intranet.timesheet.services.model.impl.TimesheetDetailsImpl
 * @see sg.com.para.intranet.timesheet.services.model.impl.TimesheetDetailsModelImpl
 * @generated
 */
public interface TimesheetDetailsModel extends BaseModel<TimesheetDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a timesheet details model instance should use the {@link TimesheetDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this timesheet details.
	 *
	 * @return the primary key of this timesheet details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this timesheet details.
	 *
	 * @param primaryKey the primary key of this timesheet details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the timesheet details ID of this timesheet details.
	 *
	 * @return the timesheet details ID of this timesheet details
	 */
	public int getTimesheetDetailsId();

	/**
	 * Sets the timesheet details ID of this timesheet details.
	 *
	 * @param timesheetDetailsId the timesheet details ID of this timesheet details
	 */
	public void setTimesheetDetailsId(int timesheetDetailsId);

	/**
	 * Returns the timesheet ID of this timesheet details.
	 *
	 * @return the timesheet ID of this timesheet details
	 */
	public int getTimesheetId();

	/**
	 * Sets the timesheet ID of this timesheet details.
	 *
	 * @param timesheetId the timesheet ID of this timesheet details
	 */
	public void setTimesheetId(int timesheetId);

	/**
	 * Returns the clock in time of this timesheet details.
	 *
	 * @return the clock in time of this timesheet details
	 */
	public Date getClockInTime();

	/**
	 * Sets the clock in time of this timesheet details.
	 *
	 * @param clockInTime the clock in time of this timesheet details
	 */
	public void setClockInTime(Date clockInTime);

	/**
	 * Returns the clock out time of this timesheet details.
	 *
	 * @return the clock out time of this timesheet details
	 */
	public Date getClockOutTime();

	/**
	 * Sets the clock out time of this timesheet details.
	 *
	 * @param clockOutTime the clock out time of this timesheet details
	 */
	public void setClockOutTime(Date clockOutTime);

	/**
	 * Returns the remarks of this timesheet details.
	 *
	 * @return the remarks of this timesheet details
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this timesheet details.
	 *
	 * @param remarks the remarks of this timesheet details
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the type of this timesheet details.
	 *
	 * @return the type of this timesheet details
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this timesheet details.
	 *
	 * @param type the type of this timesheet details
	 */
	public void setType(String type);

	/**
	 * Returns the fullday or time based of this timesheet details.
	 *
	 * @return the fullday or time based of this timesheet details
	 */
	@AutoEscape
	public String getFulldayOrTimeBased();

	/**
	 * Sets the fullday or time based of this timesheet details.
	 *
	 * @param fulldayOrTimeBased the fullday or time based of this timesheet details
	 */
	public void setFulldayOrTimeBased(String fulldayOrTimeBased);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		sg.com.para.intranet.timesheet.services.model.TimesheetDetails timesheetDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<sg.com.para.intranet.timesheet.services.model.TimesheetDetails> toCacheModel();

	@Override
	public sg.com.para.intranet.timesheet.services.model.TimesheetDetails toEscapedModel();

	@Override
	public sg.com.para.intranet.timesheet.services.model.TimesheetDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}