/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.timesheet.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimesheetMonth service. Represents a row in the &quot;intranet_timesheet_month&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link sg.com.para.intranet.timesheet.services.model.impl.TimesheetMonthModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link sg.com.para.intranet.timesheet.services.model.impl.TimesheetMonthImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see TimesheetMonth
 * @see sg.com.para.intranet.timesheet.services.model.impl.TimesheetMonthImpl
 * @see sg.com.para.intranet.timesheet.services.model.impl.TimesheetMonthModelImpl
 * @generated
 */
public interface TimesheetMonthModel extends BaseModel<TimesheetMonth> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a timesheet month model instance should use the {@link TimesheetMonth} interface instead.
	 */

	/**
	 * Returns the primary key of this timesheet month.
	 *
	 * @return the primary key of this timesheet month
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this timesheet month.
	 *
	 * @param primaryKey the primary key of this timesheet month
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the timesheet month ID of this timesheet month.
	 *
	 * @return the timesheet month ID of this timesheet month
	 */
	public int getTimesheetMonthId();

	/**
	 * Sets the timesheet month ID of this timesheet month.
	 *
	 * @param timesheetMonthId the timesheet month ID of this timesheet month
	 */
	public void setTimesheetMonthId(int timesheetMonthId);

	/**
	 * Returns the month of this timesheet month.
	 *
	 * @return the month of this timesheet month
	 */
	public int getMonth();

	/**
	 * Sets the month of this timesheet month.
	 *
	 * @param month the month of this timesheet month
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this timesheet month.
	 *
	 * @return the year of this timesheet month
	 */
	public int getYear();

	/**
	 * Sets the year of this timesheet month.
	 *
	 * @param year the year of this timesheet month
	 */
	public void setYear(int year);

	/**
	 * Returns the employee screen name of this timesheet month.
	 *
	 * @return the employee screen name of this timesheet month
	 */
	@AutoEscape
	public String getEmployeeScreenName();

	/**
	 * Sets the employee screen name of this timesheet month.
	 *
	 * @param employeeScreenName the employee screen name of this timesheet month
	 */
	public void setEmployeeScreenName(String employeeScreenName);

	/**
	 * Returns the status of this timesheet month.
	 *
	 * @return the status of this timesheet month
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this timesheet month.
	 *
	 * @param status the status of this timesheet month
	 */
	public void setStatus(String status);

	/**
	 * Returns the submitted date of this timesheet month.
	 *
	 * @return the submitted date of this timesheet month
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this timesheet month.
	 *
	 * @param submittedDate the submitted date of this timesheet month
	 */
	public void setSubmittedDate(Date submittedDate);

	/**
	 * Returns the approved by of this timesheet month.
	 *
	 * @return the approved by of this timesheet month
	 */
	@AutoEscape
	public String getApprovedBy();

	/**
	 * Sets the approved by of this timesheet month.
	 *
	 * @param approvedBy the approved by of this timesheet month
	 */
	public void setApprovedBy(String approvedBy);

	/**
	 * Returns the approved date of this timesheet month.
	 *
	 * @return the approved date of this timesheet month
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this timesheet month.
	 *
	 * @param approvedDate the approved date of this timesheet month
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the processed by of this timesheet month.
	 *
	 * @return the processed by of this timesheet month
	 */
	@AutoEscape
	public String getProcessedBy();

	/**
	 * Sets the processed by of this timesheet month.
	 *
	 * @param processedBy the processed by of this timesheet month
	 */
	public void setProcessedBy(String processedBy);

	/**
	 * Returns the processed date of this timesheet month.
	 *
	 * @return the processed date of this timesheet month
	 */
	public Date getProcessedDate();

	/**
	 * Sets the processed date of this timesheet month.
	 *
	 * @param processedDate the processed date of this timesheet month
	 */
	public void setProcessedDate(Date processedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		sg.com.para.intranet.timesheet.services.model.TimesheetMonth timesheetMonth);

	@Override
	public int hashCode();

	@Override
	public CacheModel<sg.com.para.intranet.timesheet.services.model.TimesheetMonth> toCacheModel();

	@Override
	public sg.com.para.intranet.timesheet.services.model.TimesheetMonth toEscapedModel();

	@Override
	public sg.com.para.intranet.timesheet.services.model.TimesheetMonth toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}